### ISSUE TITLE
Retour Atelier 1

### ISSUE THREAD

**Issue by nivetml** [AhmedGuetti/pascal_paoli_L3#1]
# Problème de nom de classe
La classe doit respecter les conventions de nommage
https://github.com/AhmedGuetti/pascal_paoli_L3/blob/c4315d3e2c10873e1f35bcc03ede0f49e6feec58/POO/Atelie1/src/exercice1/de.java#L7

## Pb incrémentation double de la variable de classe i
https://github.com/AhmedGuetti/pascal_paoli_L3/blob/c4315d3e2c10873e1f35bcc03ede0f49e6feec58/POO/Atelie1/src/exercice1/de.java#L20-L30
       ++i;

**Comment by AhmedGuetti** [comment]
problème présenté résolu
